# -*- coding: utf-8 -*-
"""
Created on Tue Nov 10 00:55:54 2020

@author: gonza
"""
from componentes import *
from string import ascii_letters

a = OpAsigna(14)
print(a)
b = OpAdd(16)
print(b)
c = OpSub(18)
print(c)
d = OpMult(20)
print(d)
e = OpDiv(22)
print(e)
f = OpMod(24)
print(f)
g1 = Numero(3,None,26)
print(g1)
g2 = Numero(3,14,28)
print(g2)
h1 = Identif('A325',30)
print (h1)
h2 = Identif('325',32)
print (h2)
h3 = Identif('PROGRAMA',34)
print (h3)
i1 = PR('PROGRAMA',36)
print (i1)
i2 = PR('HOLA',38)
print (i2)
j1 = OpRel('<>',40)
print (j1)
j2 = OpRel('*',42)
print (j2)
k = ComentarioLineal(44)
print(k)
l = EspacioEnBlanco(46)
print(l)
m = DosPuntos(48)
print(m)
n = PuntoyComa(50)
print(n)
o = Coma(52)
print(o)
p = CorcheteA(54)
print(p)
q = CorcheteC(56)
print(q)
r = ParentesisA(58)
print(r)
s = ParentesisC(60)
print(s)
